# General

site_name: Frictionless Application
site_url: https://application.frictionlessdata.io
site_author: Open Knowledge Foundation
site_description: Data management for humans
repo_name: frictionlessdata/application
repo_url: https://github.com/frictionlessdata/application
copyright: Copyright &copy; 2022 Open Knowledge Foundation

# Theme

theme:
  name: material
  custom_dir: docs/.theme
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    # - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.png
  favicon: assets/favicon.png

# Plugins

# plugins:
  # - minify:
      # minify_html: true

# Extras

extra:
  annotate:
    json: [.s2]
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

# Extensions

markdown_extensions:
  - tables
  - toc:
      permalink: true
      title: Page contents
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.extra
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      check_paths: true

# Navigation

nav:
  - Home:
      Welcome: index.md
      Installation: installation.md
  - Integrating:
      Library: integrating/library.md
  - Contributing:
      Development: contributing/development.md

